Refactor & cleanup
finleap-connect/monoskope pull request #156
Opened 2022-05-24 08:52 UTC by jastBytes

Using new go 1.18 features to cleanup and refactor.

2022-05-27 11:15 UTC, HaniAlshikh requested changes

2022-05-27 11:15 UTC, HaniAlshikh commented on pkg/domain/repositories/user_repo.go
>  	// ById searches for the a user projection by it's id.
ById -> ByUserId

2022-05-27 11:15 UTC, HaniAlshikh commented on pkg/domain/repositories/user_repo.go
>  // ById searches for the a user projection by it's id.
ById -> ByUserId

2022-05-27 11:15 UTC, HaniAlshikh commented on pkg/domain/repositories/user_repo.go
> +// ByEmail searches for the a user projection by it's email address.
ByEmail searches for the a user ... -> ByEmail searches for the user ...

2022-05-27 11:15 UTC, HaniAlshikh commented on pkg/domain/repositories/user_role_binding.go
>  // Repository is a repository for reading and writing UserRoleBinding projections.
Repository -> UserRoleBindingRepository

2022-05-27 11:15 UTC, HaniAlshikh commented on pkg/domain/repositories/user_role_binding.go
>  // NewUserRepository creates a repository for reading and writing UserRoleBinding projections.
NewUserRepository -> NewUserRoleBindingRepository

2022-06-03 13:14 UTC, jastBytes commented on pkg/audit/formatters/formatter_base.go
> +// Snapshotter is the base implementation for all audit formatters
Renamed it and adjusted comment.

2022-06-03 13:14 UTC, jastBytes commented on internal/integration_test.go
> +	// Context("cert management", func() {
I was lazy and just commented it since it did not work (for a reason I do not understand). But will fix this first.

2022-06-03 13:34 UTC, jastBytes commented on internal/integration_test.go
> +	// Context("cert management", func() {
Fixed

2022-06-08 09:17 UTC, HaniAlshikh reviewed
you missed the hidden conversions :)

2022-06-15 08:12 UTC, HaniAlshikh approved these changes

2022-06-15 08:13 UTC, merged