Make creating a command with data simpler
finleap-connect/monoskope pull request #245
Opened 2022-09-20 08:39 UTC by jastBytes

This PR simpyfies the creation of new commands with command data attached.

2022-09-20 11:59 UTC, HaniAlshikh requested changes

2022-09-26 10:00 UTC, jastBytes commented on pkg/domain/commands/api_command_factory.go
> -func AddCommandData(command *esApi.Command, commandData protoreflect.ProtoMessage) (*esApi.Command, error) {
NewCommand has stayed because there are certain commands like deleting which do not need any data.

2022-09-26 10:22 UTC, HaniAlshikh commented on pkg/domain/commands/api_command_factory.go
> -func AddCommandData(command *esApi.Command, commandData protoreflect.ProtoMessage) (*esApi.Command, error) {
Oh yea right 👍

2022-09-26 10:22 UTC, HaniAlshikh approved these changes

2022-09-26 10:56 UTC, merged